[package]
name = "vex-sdk-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bitflags = "2.5.0"
bytemuck = "1.15.0"
bytes = "1.6.0"
ctrlc = "3.4.4"
fimg = { version = "0.4.41", features = ["save"], default-features = false }
png = "0.17.13"
resource = "0.5.0"
rusttype = "0.9.3"
sdl2 = "0.36.0"
single_value_channel = "1.2.2"
wasmparser = "0.205.0"
wasmtime = { version = "20.0.0", default-features = false, features = [
    # "cache",
    "parallel-compilation",
    "cranelift",
    # "pooling-allocator",
    "demangle",
    "addr2line",
    "coredump",
    "debug-builtins",
    "runtime",
] }
