[package]
name = "vex-sdk-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bitflags = "2.5.0"
bytes = "1.6.0"
piet = { version = "0.6.2", features = ["png"], path = "../piet/piet" }
piet-common = { version = "0.6.2", features = [
    "png",
], path = "../piet/piet-common" }
png = "0.17.13"
sdl2 = "0.36.0"
wasmparser = "0.203.0"
wasmtime = { version = "19.0.2", default-features = false, features = [
    # "cache",
    "parallel-compilation",
    "cranelift",
    # "pooling-allocator",
    "demangle",
    "addr2line",
    "coredump",
    "debug-builtins",
    "runtime",
] }
